
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinic
 */
public class Operadores6 extends javax.swing.JFrame {

    /**
     * Creates new form operadores
     */
    public Operadores6() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("img/icone.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        statusQuestao1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        alternativa4 = new javax.swing.JRadioButton();
        alternativa3 = new javax.swing.JRadioButton();
        alternativa2 = new javax.swing.JRadioButton();
        correta = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("trabalhocaio");
        setMinimumSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setText("Menu");
        jButton2.setToolTipText("Clique para retornar ao Menu inicial");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusCycleRoot(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 560, 70, 30);

        statusQuestao1.setToolTipText("");
        getContentPane().add(statusQuestao1);
        statusQuestao1.setBounds(520, 220, 30, 30);

        jButton3.setToolTipText("Clique para ir para a próxima tela");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusCycleRoot(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 450, 50, 70);

        alternativa4.setBackground(new java.awt.Color(255, 255, 255));
        alternativa4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alternativa4.setText("14");
        alternativa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa4ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa4);
        alternativa4.setBounds(410, 290, 50, 31);

        alternativa3.setBackground(new java.awt.Color(255, 255, 255));
        alternativa3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alternativa3.setText("5");
        alternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3);
        alternativa3.setBounds(300, 290, 50, 31);

        alternativa2.setBackground(new java.awt.Color(255, 255, 255));
        alternativa2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alternativa2.setText("10");
        alternativa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2);
        alternativa2.setBounds(160, 290, 50, 31);

        correta.setBackground(new java.awt.Color(255, 255, 255));
        correta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        correta.setText("7");
        correta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corretaActionPerformed(evt);
            }
        });
        getContentPane().add(correta);
        correta.setBounds(50, 290, 35, 31);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone_executar.png"))); // NOI18N
        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 450, 120, 41);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("3) Analisando o código abaixo:\ninicio\n a := 5\n a := 2 + a\n\n escreva(\"A = \", a)\nfimalgoritmo\n\n Qual será o resultado de a?\n");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setName(""); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 60, 720, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telaTexto2.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(832, 630));
        jLabel1.setMinimumSize(new java.awt.Dimension(832, 630));
        jLabel1.setPreferredSize(new java.awt.Dimension(832, 630));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu Mn = new Menu();
        Mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);

        Operadores7 next = new Operadores7();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(correta.isSelected()){
            statusQuestao1.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_acerto.png")));

        }else {
            statusQuestao1.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_erro.png")));
        }
        
        if(correta.isSelected()){
            jButton3.setIcon((Icon) new ImageIcon(getClass().getResource("img/btnProximo.png")));
            JOptionPane.showMessageDialog(null, "Parabens! Clique no botão para ir a próxima tela.");
        }else{
            JOptionPane.showMessageDialog(null, "Qestão incorreta tente novamente");
            Operadores6 next = new Operadores6();
            next.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void alternativa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa4ActionPerformed
        // TODO add your handling code here:
        if(alternativa4.isSelected()){
            correta.setSelected(false);
            alternativa3.setSelected(false);
            alternativa2.setSelected(false);
        }
    }//GEN-LAST:event_alternativa4ActionPerformed

    private void alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3ActionPerformed
        // TODO add your handling code here:
        if(alternativa3.isSelected()){
            correta.setSelected(false);
            alternativa2.setSelected(false);
            alternativa4.setSelected(false);
        }
    }//GEN-LAST:event_alternativa3ActionPerformed

    private void alternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2ActionPerformed
        // TODO add your handling code here:
        if(alternativa2.isSelected()){
            correta.setSelected(false);
            alternativa3.setSelected(false);
            alternativa4.setSelected(false);
        }
    }//GEN-LAST:event_alternativa2ActionPerformed

    private void corretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corretaActionPerformed
        // TODO add your handling code here:
        if(correta.isSelected()){
            alternativa2.setSelected(false);
            alternativa3.setSelected(false);
            alternativa4.setSelected(false);

        }
    }//GEN-LAST:event_corretaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operadores1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alternativa2;
    private javax.swing.JRadioButton alternativa3;
    private javax.swing.JRadioButton alternativa4;
    private javax.swing.JRadioButton correta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel statusQuestao1;
    // End of variables declaration//GEN-END:variables
}
