
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vinic
 */
public class Operadores5 extends javax.swing.JFrame {

    /**
     * Creates new form operadores
     */
    public Operadores5() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("img/icone.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        alternativa1 = new javax.swing.JRadioButton();
        alternativa3 = new javax.swing.JRadioButton();
        alternativa2 = new javax.swing.JRadioButton();
        alternativacerta1 = new javax.swing.JRadioButton();
        statusQuestao1 = new javax.swing.JLabel();
        statusQuestao2 = new javax.swing.JLabel();
        Falso = new javax.swing.JRadioButton();
        verdadeiro = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("trabalhocaio");
        setMinimumSize(new java.awt.Dimension(800, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Quiz de Fixação");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 40, 190, 50);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone_executar.png"))); // NOI18N
        jButton4.setText("Enviar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 450, 120, 41);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton2.setText("Menu");
        jButton2.setToolTipText("Clique para retornar ao Menu inicial");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusCycleRoot(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 560, 70, 30);

        jButton3.setToolTipText("Clique para ir para a próxima tela");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusCycleRoot(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 440, 50, 70);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 260, 720, 10);

        alternativa1.setBackground(new java.awt.Color(255, 255, 255));
        alternativa1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternativa1.setText("*");
        alternativa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa1);
        alternativa1.setBounds(60, 200, 50, 33);

        alternativa3.setBackground(new java.awt.Color(255, 255, 255));
        alternativa3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternativa3.setText("+");
        alternativa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3);
        alternativa3.setBounds(320, 200, 50, 33);

        alternativa2.setBackground(new java.awt.Color(255, 255, 255));
        alternativa2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternativa2.setText("/");
        alternativa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2);
        alternativa2.setBounds(190, 200, 50, 33);

        alternativacerta1.setBackground(new java.awt.Color(255, 255, 255));
        alternativacerta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alternativacerta1.setText("$");
        alternativacerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativacerta1ActionPerformed(evt);
            }
        });
        getContentPane().add(alternativacerta1);
        alternativacerta1.setBounds(460, 200, 50, 33);

        statusQuestao1.setToolTipText("");
        getContentPane().add(statusQuestao1);
        statusQuestao1.setBounds(560, 160, 30, 30);

        statusQuestao2.setToolTipText("");
        getContentPane().add(statusQuestao2);
        statusQuestao2.setBounds(540, 320, 30, 30);

        Falso.setBackground(new java.awt.Color(255, 255, 255));
        Falso.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Falso.setText("Falso");
        Falso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FalsoActionPerformed(evt);
            }
        });
        getContentPane().add(Falso);
        Falso.setBounds(340, 340, 120, 30);

        verdadeiro.setBackground(new java.awt.Color(255, 255, 255));
        verdadeiro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        verdadeiro.setText("Verdadeiro");
        verdadeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdadeiroActionPerformed(evt);
            }
        });
        getContentPane().add(verdadeiro);
        verdadeiro.setBounds(60, 340, 120, 30);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("2) Em operadores aritméticos o simbolo de ++ é o sinal de decremento ou seja que subtrai 1\ndo valor da variavel?");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jTextArea2.setName(""); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 280, 720, 60);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Muito bem, vamos treinar! Apos responder, clica no botão enviar.\n\n1) Qual desses sinais não faz parte dos operadores aritméticos?");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 720, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telaTexto2.png"))); // NOI18N
        jLabel1.setText("fundo");
        jLabel1.setMaximumSize(new java.awt.Dimension(832, 630));
        jLabel1.setMinimumSize(new java.awt.Dimension(832, 630));
        jLabel1.setPreferredSize(new java.awt.Dimension(832, 630));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu Mn = new Menu();
        Mn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1ActionPerformed
        // TODO add your handling code here:
        if(alternativa1.isSelected()){
            alternativacerta1.setSelected(false);
            alternativa2.setSelected(false);
            alternativa3.setSelected(false);       
        }
            
    }//GEN-LAST:event_alternativa1ActionPerformed

    private void alternativacerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativacerta1ActionPerformed
        // TODO add your handling code here:
        if(alternativacerta1.isSelected()){
            alternativa1.setSelected(false);
            alternativa2.setSelected(false);
            alternativa3.setSelected(false);            
        }
    }//GEN-LAST:event_alternativacerta1ActionPerformed

    private void alternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2ActionPerformed
        // TODO add your handling code here:
        if(alternativa2.isSelected()){
            alternativa1.setSelected(false);
            alternativacerta1.setSelected(false);
            alternativa3.setSelected(false);  
        }
    }//GEN-LAST:event_alternativa2ActionPerformed

    private void alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3ActionPerformed
        // TODO add your handling code here:
        if(alternativa3.isSelected()){
            alternativa1.setSelected(false);
            alternativa2.setSelected(false);
            alternativacerta1.setSelected(false);    
        }
    }//GEN-LAST:event_alternativa3ActionPerformed

    private void verdadeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdadeiroActionPerformed
        // TODO add your handling code here:
        
        if(verdadeiro.isSelected()){
            Falso.setSelected(false);
        
        }
    }//GEN-LAST:event_verdadeiroActionPerformed

    private void FalsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FalsoActionPerformed
        // TODO add your handling code here:
         if(Falso.isSelected()){
            verdadeiro.setSelected(false);
         }
    }//GEN-LAST:event_FalsoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(alternativacerta1.isSelected()){
            statusQuestao1.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_acerto.png")));
            
        }else {
            statusQuestao1.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_erro.png")));
        }
         if(Falso.isSelected()){
            statusQuestao2.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_acerto.png")));
            
        }else {
            statusQuestao2.setIcon((Icon) new ImageIcon(getClass().getResource("img/icon_erro.png")));
        }
        if(alternativacerta1.isSelected()&& Falso.isSelected()){
        jButton3.setIcon((Icon) new ImageIcon(getClass().getResource("img/btnProximo.png")));
        JOptionPane.showMessageDialog(null, "Parabens! Clique no botão para ir a próxima tela.");        
        }else{
        JOptionPane.showMessageDialog(null, "Uma ou mais questões estão incorretas tente novamente");
        Operadores5 next = new Operadores5();
        next.setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        Operadores6 next = new Operadores6();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operadores1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operadores1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Falso;
    private javax.swing.JRadioButton alternativa1;
    private javax.swing.JRadioButton alternativa2;
    private javax.swing.JRadioButton alternativa3;
    private javax.swing.JRadioButton alternativacerta1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel statusQuestao1;
    private javax.swing.JLabel statusQuestao2;
    private javax.swing.JRadioButton verdadeiro;
    // End of variables declaration//GEN-END:variables
}
